---
title: "ICES Stocks - JABBA Inputs"
author: "L Kell"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ICES Stocks - JABBA Inputs}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
bibliography: refs.bib
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  eval = TRUE,
  cache = TRUE,
  cache.path = "cache/jabba-inputs-",
  fig.path = "figures/jabba-inputs-",
  fig.width = 10,
  fig.height = 12,
  dev = "png"
)

iFig <- 0
iTab <- 0
```

```{r, libraries}
library(icesdata)
library(FLCore)
library(FLasher)
library(FLBRP)
library(FLife)
library(plyr)
library(dplyr)
library(reshape2)
library(ggplot2)
library(scales)
library(ggpubr)

if (requireNamespace("FLCandy", quietly = TRUE)) {
  library(FLCandy)
}
```

## Introduction

ICES Category 1 stock assessments, analytical age based assessments that have been benchmarked.

This vignette demonstrates the preparation of inputs for JABBA stock assessment models.

**Note:** This vignette requires external data files and JABBA utility functions.

```{r, source, eval=FALSE}
# External source files needed for JABBA inputs
# source("C:/active/jabba-z/source/jabba-utils.R")
```

```{r, data-load}
formas_data_dir <- get_vignette_data_dir()
if (is.null(formas_data_dir)) {
  formas_data_dir <- system.file("formas/data", package = "icesdata")
  if (!dir.exists(formas_data_dir) && dir.exists("formas/data")) {
    formas_data_dir <- "formas/data"
  }
}

# Load ICES stocks data
if (!is.null(formas_data_dir)) {
  inputs_dir <- file.path(formas_data_dir, "inputs")
  stock_files <- c(
    "Updated_stks_n82_R0_updated202408.RData",
    "Updated_stks_n81_R0_updated2023.RData"
  )
  
  for (stock_file in stock_files) {
    stocks_file <- file.path(inputs_dir, stock_file)
    if (file.exists(stocks_file)) {
      load(stocks_file, envir = .GlobalEnv)
      break
    }
  }
}
```

### Priors

```{r, priors, eval=exists("ICESStocks") && exists("priorFn")}
if (exists("ICESStocks") && exists("priorFn")) {
  priors <- plyr::ldply(ICESStocks, priorFn)
  
  if (!is.null(formas_data_dir)) {
    save(priors, file = file.path(formas_data_dir, "priors.RData"))
  }
}
```

#### Time series

```{r, tseries, eval=exists("ICESStocks") && exists("dataFn")}
if (exists("ICESStocks") && exists("dataFn")) {
  tseries <- plyr::ldply(ICESStocks, dataFn)
  
  if (!is.null(formas_data_dir)) {
    save(tseries, file = file.path(formas_data_dir, "tseries.RData"))
  }
}
```

